### ISSUE TITLE
Fix inability to see restricted pages when logged in

### ISSUE THREAD

**Issue by 1cookspe** [NewPath-Consulting/WA4WP-Beta#25]
When logged in, even when a specific page is set to be accessed by a user group, the user is given the restriction message. Could it be related to cookies or cross site tracking?

**Comment by kendrakleber** [comment]
This was caused by the userstatus_new field in the user meta data being empty (userstatus_new";a:1:{i:0;N;}), thus the user would not match any allowed member statuses. 

 This occured on bchpca and dns.newpath, but not dns staging, unclear why. Maybe something went wrong with the code on ~650 of bundle plugin: `$stausvlaue = $responsear[0]-&gt;status;                update_user_meta($user-&gt;ID, 'userstatus_new', $stausvlaue);`. Interestingly, if the user was signed in to WP and then tried to view the page, it seemed to work once.

The user WA status was also in the user meta as an array in string form, so I changed the code to get the status from there instead using a regular expression. Also, the WP side expected PendingLevel, but the WA side would pass PendingUpdrade, so this is automatically converted. 

This is kind of a hack-y fix, but it seems to work.
